#ifdef MOD_ENUMS
        #define DECLARE_MOD( mod ) mod
#endif

#ifdef MOD_STRINGS
        #define DECLARE_MOD( mod ) #mod
#endif

DECLARE_MOD( MOD_UNKNOWN ),
DECLARE_MOD( MOD_SHOTGUN ),
DECLARE_MOD( MOD_BLASTER ),
DECLARE_MOD( MOD_PAINSAW ),
DECLARE_MOD( MOD_MACHINEGUN ),
DECLARE_MOD( MOD_CHAINGUN ),
DECLARE_MOD( MOD_PRIFLE ),
DECLARE_MOD( MOD_MDRIVER ),
DECLARE_MOD( MOD_LASGUN ),
DECLARE_MOD( MOD_LCANNON ),
DECLARE_MOD( MOD_LCANNON_SPLASH ),
DECLARE_MOD( MOD_FLAMER ),
DECLARE_MOD( MOD_FLAMER_SPLASH ),
DECLARE_MOD( MOD_GRENADE ),
DECLARE_MOD( MOD_WATER ),
DECLARE_MOD( MOD_SLIME ),
DECLARE_MOD( MOD_LAVA ),
DECLARE_MOD( MOD_CRUSH ),
DECLARE_MOD( MOD_TELEFRAG ),
DECLARE_MOD( MOD_FALLING ),
DECLARE_MOD( MOD_SUICIDE ),
DECLARE_MOD( MOD_TARGET_LASER ),
DECLARE_MOD( MOD_TRIGGER_HURT ),

DECLARE_MOD( MOD_ABUILDER_CLAW ),
DECLARE_MOD( MOD_LEVEL0_BITE ),
DECLARE_MOD( MOD_LEVEL1_CLAW ),
DECLARE_MOD( MOD_LEVEL1_PCLOUD ),
DECLARE_MOD( MOD_LEVEL3_CLAW ),
DECLARE_MOD( MOD_LEVEL3_POUNCE ),
DECLARE_MOD( MOD_LEVEL3_BOUNCEBALL ),
DECLARE_MOD( MOD_LEVEL2_CLAW ),
DECLARE_MOD( MOD_LEVEL2_ZAP ),
DECLARE_MOD( MOD_LEVEL4_CLAW ),
DECLARE_MOD( MOD_LEVEL4_CHARGE ),

DECLARE_MOD( MOD_SLOWBLOB ),
DECLARE_MOD( MOD_POISON ),
DECLARE_MOD( MOD_SWARM ),

DECLARE_MOD( MOD_HSPAWN ),
DECLARE_MOD( MOD_TESLAGEN ),
DECLARE_MOD( MOD_MGTURRET ),
DECLARE_MOD( MOD_REACTOR ),

DECLARE_MOD( MOD_ASPAWN ),
DECLARE_MOD( MOD_ATUBE ),
DECLARE_MOD( MOD_OVERMIND )

#ifdef MOD_ENUMS
        , DECLARE_MOD( MOD_NUM_MAX )
#endif

#undef DECLARE_MOD
