#ifdef EVENT_ENUMS
        #define DECLARE_EVENT( ev ) ev
#endif

#ifdef EVENT_STRINGS
        #define DECLARE_EVENT( ev ) #ev
#endif

DECLARE_EVENT( EV_NONE ),

DECLARE_EVENT( EV_FOOTSTEP ),
DECLARE_EVENT( EV_FOOTSTEP_METAL ),
DECLARE_EVENT( EV_FOOTSTEP_SQUELCH ),
DECLARE_EVENT( EV_FOOTSPLASH ),
DECLARE_EVENT( EV_FOOTWADE ),
DECLARE_EVENT( EV_SWIM ),

DECLARE_EVENT( EV_STEP_4 ),
DECLARE_EVENT( EV_STEP_8 ),
DECLARE_EVENT( EV_STEP_12 ),
DECLARE_EVENT( EV_STEP_16 ),

DECLARE_EVENT( EV_STEPDN_4 ),
DECLARE_EVENT( EV_STEPDN_8 ),
DECLARE_EVENT( EV_STEPDN_12 ),
DECLARE_EVENT( EV_STEPDN_16 ),

DECLARE_EVENT( EV_FALL_SHORT ),
DECLARE_EVENT( EV_FALL_MEDIUM ),
DECLARE_EVENT( EV_FALL_FAR ),
DECLARE_EVENT( EV_FALLING ),

DECLARE_EVENT( EV_JUMP ),
DECLARE_EVENT( EV_WATER_TOUCH ), // foot touches
DECLARE_EVENT( EV_WATER_LEAVE ), // foot leaves
DECLARE_EVENT( EV_WATER_UNDER ), // head touches
DECLARE_EVENT( EV_WATER_CLEAR ), // head leaves

DECLARE_EVENT( EV_NOAMMO ),
DECLARE_EVENT( EV_CHANGE_WEAPON ),
DECLARE_EVENT( EV_FIRE_WEAPON ),
DECLARE_EVENT( EV_FIRE_WEAPON2 ),
DECLARE_EVENT( EV_FIRE_WEAPON3 ),

DECLARE_EVENT( EV_PLAYER_RESPAWN ), //TA: for fovwarp effects
DECLARE_EVENT( EV_PLAYER_TELEPORT_IN ),
DECLARE_EVENT( EV_PLAYER_TELEPORT_OUT ),

DECLARE_EVENT( EV_GRENADE_BOUNCE ),    // eventParm will be the soundindex

DECLARE_EVENT( EV_GENERAL_SOUND ),
DECLARE_EVENT( EV_GLOBAL_SOUND ),    // no attenuation

DECLARE_EVENT( EV_BULLET_HIT_FLESH ),
DECLARE_EVENT( EV_BULLET_HIT_WALL ),

DECLARE_EVENT( EV_SHOTGUN ),

DECLARE_EVENT( EV_MISSILE_HIT ),
DECLARE_EVENT( EV_MISSILE_MISS ),
DECLARE_EVENT( EV_MISSILE_MISS_METAL ),
DECLARE_EVENT( EV_TESLATRAIL ),
DECLARE_EVENT( EV_BULLET ),        // otherEntity is the shooter

DECLARE_EVENT( EV_LEV1_GRAB ),
DECLARE_EVENT( EV_LEV4_CHARGE_PREPARE ),
DECLARE_EVENT( EV_LEV4_CHARGE_START ),

DECLARE_EVENT( EV_PAIN ),
DECLARE_EVENT( EV_DEATH1 ),
DECLARE_EVENT( EV_DEATH2 ),
DECLARE_EVENT( EV_DEATH3 ),
DECLARE_EVENT( EV_OBITUARY ),

DECLARE_EVENT( EV_GIB_PLAYER ),      // gib a previously living player

DECLARE_EVENT( EV_BUILD_CONSTRUCT ), //TA
DECLARE_EVENT( EV_BUILD_DESTROY ),   //TA
DECLARE_EVENT( EV_BUILD_DELAY ),     //TA: can't build yet
DECLARE_EVENT( EV_BUILD_REPAIR ),    //TA: repairing buildable
DECLARE_EVENT( EV_BUILD_REPAIRED ),  //TA: buildable has full health
DECLARE_EVENT( EV_HUMAN_BUILDABLE_EXPLOSION ),
DECLARE_EVENT( EV_ALIEN_BUILDABLE_EXPLOSION ),
DECLARE_EVENT( EV_ALIEN_ACIDTUBE ),

DECLARE_EVENT( EV_MEDKIT_USED ),

DECLARE_EVENT( EV_ALIEN_EVOLVE ),
DECLARE_EVENT( EV_ALIEN_EVOLVE_FAILED ),

DECLARE_EVENT( EV_DEBUG_LINE ),
DECLARE_EVENT( EV_STOPLOOPINGSOUND ),
DECLARE_EVENT( EV_TAUNT ),

DECLARE_EVENT( EV_OVERMIND_ATTACK ), //TA: overmind under attack
DECLARE_EVENT( EV_OVERMIND_DYING ),  //TA: overmind close to death
DECLARE_EVENT( EV_OVERMIND_SPAWNS ), //TA: overmind needs spawns

DECLARE_EVENT( EV_DCC_ATTACK ),      //TA: dcc under attack

DECLARE_EVENT( EV_RPTUSE_SOUND )     //TA: trigger a sound

#ifdef EVENT_ENUMS
         , DECLARE_EVENT( EV_MAX )
#endif

#undef DECLARE_EVENT
