#if defined(EXTERN_CG_CVAR)
#define CG_CVAR(vmCvar, cvarName, defaultString, cvarFlags) extern vmCvar_t vmCvar;
#endif

#if defined(DECLARE_CG_CVAR)
#define CG_CVAR(vmCvar, cvarName, defaultString, cvarFlags) vmCvar_t vmCvar;
#endif

#if defined(CG_CVAR_LIST)
#define CG_CVAR(vmCvar, cvarName, defaultString, cvarFlags) {&vmCvar, cvarName, defaultString, cvarFlags},
#endif

CG_CVAR(cg_ignore, "cg_ignore", "0", 0) //used for debugging
CG_CVAR(cg_autoswitch, "cg_autoswitch", "1", CVAR_ARCHIVE)
CG_CVAR(cg_drawGun, "cg_drawGun", "1", CVAR_ARCHIVE)
CG_CVAR(cg_zoomFov, "cg_zoomfov", "22.5", CVAR_ARCHIVE)
CG_CVAR(cg_fov, "cg_fov", "90", CVAR_ARCHIVE)
CG_CVAR(cg_fovAdjust, "cg_fovAdjust", "1", CVAR_ARCHIVE)
CG_CVAR(cg_fovCustom, "cg_fovCustom", "0", CVAR_ARCHIVE)
CG_CVAR(cg_lanternLight, "cg_lanternLight", "0", CVAR_ARCHIVE)
CG_CVAR(cg_lanternLightColorRed, "cg_lanternLightColorRed", "1.0", CVAR_ARCHIVE)
CG_CVAR(cg_lanternLightColorGreen, "cg_lanternLightColorGreen", "1.0", CVAR_ARCHIVE)
CG_CVAR(cg_lanternLightColorBlue, "cg_lanternLightColorBlue", "1.0", CVAR_ARCHIVE)
CG_CVAR(cg_lanternLightRadius, "cg_lanternLightRadius", "400.0", CVAR_ARCHIVE)
CG_CVAR(cg_viewsize, "cg_viewsize", "100", CVAR_ARCHIVE)
CG_CVAR(cg_stereoSeparation, "cg_stereoSeparation", "0.4", CVAR_ARCHIVE)
CG_CVAR(cg_shadows, "cg_shadows", "1", CVAR_ARCHIVE)
CG_CVAR(cg_scanner, "cg_scanner", "1", CVAR_ARCHIVE)
CG_CVAR(cg_sense, "cg_sense", "1", CVAR_ARCHIVE)
CG_CVAR(cg_gibs, "cg_gibs", "1", CVAR_ARCHIVE)
CG_CVAR(cg_draw2D, "cg_draw2D", "1", CVAR_ARCHIVE)
CG_CVAR(cg_drawStatus, "cg_drawStatus", "1", CVAR_ARCHIVE)
CG_CVAR(cg_drawTimer, "cg_drawTimer", "1", CVAR_ARCHIVE)
CG_CVAR(cg_drawClock, "cg_drawClock", "0", CVAR_ARCHIVE)
CG_CVAR(cg_drawFPS, "cg_drawFPS", "1", CVAR_ARCHIVE)
CG_CVAR(cg_drawDemoState, "cg_drawDemoState", "1", CVAR_ARCHIVE)
CG_CVAR(cg_drawSnapshot, "cg_drawSnapshot", "0", CVAR_ARCHIVE)
CG_CVAR(cg_draw3dIcons, "cg_draw3dIcons", "1", CVAR_ARCHIVE)
CG_CVAR(cg_drawIcons, "cg_drawIcons", "1", CVAR_ARCHIVE)
CG_CVAR(cg_drawAmmoWarning, "cg_drawAmmoWarning", "1", CVAR_ARCHIVE)
CG_CVAR(cg_drawAttacker, "cg_drawAttacker", "1", CVAR_ARCHIVE)
CG_CVAR(cg_drawCrosshair, "cg_drawCrosshair", "1", CVAR_ARCHIVE)
CG_CVAR(cg_drawCrosshairNames, "cg_drawCrosshairNames", "1", CVAR_ARCHIVE)
CG_CVAR(cg_drawRewards, "cg_drawRewards", "1", CVAR_ARCHIVE)
CG_CVAR(cg_crosshairX, "cg_crosshairX", "0", CVAR_ARCHIVE)
CG_CVAR(cg_crosshairY, "cg_crosshairY", "0", CVAR_ARCHIVE)
CG_CVAR(cg_brassTime, "cg_brassTime", "2500", CVAR_ARCHIVE)
CG_CVAR(cg_simpleItems, "cg_simpleItems", "0", CVAR_ARCHIVE)
CG_CVAR(cg_addMarks, "cg_marks", "1", CVAR_ARCHIVE)
CG_CVAR(cg_lagometer, "cg_lagometer", "0", CVAR_ARCHIVE)
CG_CVAR(cg_teslaTrailTime, "cg_teslaTrailTime", "250", CVAR_ARCHIVE)
CG_CVAR(cg_railTrailTime, "cg_railTrailTime", "400", CVAR_ARCHIVE)
CG_CVAR(cg_gun_frame, "cg_gun_frame", "0", CVAR_CHEAT)
CG_CVAR(cg_gun_x, "cg_gunX", "0", CVAR_ARCHIVE)
CG_CVAR(cg_gun_y, "cg_gunY", "0", CVAR_ARCHIVE)
CG_CVAR(cg_gun_z, "cg_gunZ", "0", CVAR_ARCHIVE)
CG_CVAR(cg_centertime, "cg_centertime", "3", CVAR_CHEAT)
CG_CVAR(cg_runpitch, "cg_runpitch", "0.002", CVAR_ARCHIVE)
CG_CVAR(cg_runroll, "cg_runroll", "0.005", CVAR_ARCHIVE)
CG_CVAR(cg_bobup , "cg_bobup", "0.005", CVAR_CHEAT)
CG_CVAR(cg_bobpitch, "cg_bobpitch", "0.002", CVAR_ARCHIVE)
CG_CVAR(cg_bobroll, "cg_bobroll", "0.002", CVAR_ARCHIVE)
CG_CVAR(cg_swingSpeed, "cg_swingSpeed", "0.3", CVAR_CHEAT)
CG_CVAR(cg_animSpeed, "cg_animspeed", "1", CVAR_CHEAT)
CG_CVAR(cg_debugAnim, "cg_debuganim", "0", CVAR_CHEAT)
CG_CVAR(cg_debugPosition, "cg_debugposition", "0", CVAR_CHEAT)
CG_CVAR(cg_debugEvents, "cg_debugevents", "0", CVAR_CHEAT)
CG_CVAR(cg_errorDecay, "cg_errordecay", "100", 0)
CG_CVAR(cg_nopredict, "cg_nopredict", "0", 0)
CG_CVAR(cg_debugMove, "cg_debugMove", "0", 0)
CG_CVAR(cg_noPlayerAnims, "cg_noplayeranims", "0", CVAR_CHEAT)
CG_CVAR(cg_showmiss, "cg_showmiss", "0", 0)
CG_CVAR(cg_footsteps, "cg_footsteps", "1", CVAR_CHEAT)
CG_CVAR(cg_tracerChance, "cg_tracerchance", "0.4", CVAR_CHEAT)
CG_CVAR(cg_tracerWidth, "cg_tracerwidth", "1", CVAR_CHEAT)
CG_CVAR(cg_tracerLength, "cg_tracerlength", "100", CVAR_CHEAT)
CG_CVAR(cg_thirdPersonRange, "cg_thirdPersonRange", "40", CVAR_CHEAT)
CG_CVAR(cg_thirdPersonAngle, "cg_thirdPersonAngle", "0", CVAR_CHEAT)
CG_CVAR(cg_thirdPerson, "cg_thirdPerson", "0", CVAR_CHEAT)
CG_CVAR(cg_cameraEyes, "cg_cameraEyes", "0", CVAR_CHEAT)
CG_CVAR(cg_cameraEyes_Fwd, "cg_cameraEyes_Fwd", "-2", CVAR_CHEAT)
CG_CVAR(cg_cameraEyes_Up, "cg_cameraEyes_Up", "7", CVAR_CHEAT)
CG_CVAR(cg_forceModel, "cg_forceModel", "0", CVAR_ARCHIVE)
CG_CVAR(cg_predictItems, "cg_predictItems", "1", CVAR_ARCHIVE)
CG_CVAR(cg_deferPlayers, "cg_deferPlayers", "1", CVAR_ARCHIVE)
CG_CVAR(cg_drawTeamOverlay, "cg_drawTeamOverlay", "0", CVAR_ARCHIVE)
CG_CVAR(cg_teamOverlayUserinfo, "teamoverlay", "0", CVAR_ROM | CVAR_USERINFO)
CG_CVAR(cg_stats, "cg_stats", "0", 0)
CG_CVAR(cg_drawFriend, "cg_drawFriend", "1", CVAR_ARCHIVE)
CG_CVAR(cg_teamChatsOnly, "cg_teamChatsOnly", "0", CVAR_ARCHIVE)
CG_CVAR(cg_noVoiceChats, "cg_noVoiceChats", "0", CVAR_ARCHIVE)
CG_CVAR(cg_noVoiceText, "cg_noVoiceText", "0", CVAR_ARCHIVE)
CG_CVAR(cg_creepRes, "cg_creepRes", "16", CVAR_ARCHIVE)
CG_CVAR(cg_drawSurfNormal, "cg_drawSurfNormal", "0", CVAR_CHEAT)
CG_CVAR(cg_drawBBOX, "cg_drawBBOX", "0", CVAR_CHEAT)
CG_CVAR(cg_debugAlloc, "cg_debugAlloc", "0", 0)
CG_CVAR(cg_wwSmoothTime, "cg_wwSmoothTime", "300", CVAR_ARCHIVE)
CG_CVAR(cg_wwFollow, "cg_wwFollow", "1", CVAR_ARCHIVE|CVAR_USERINFO)
CG_CVAR(cg_wwToggle, "cg_wwToggle", "1", CVAR_ARCHIVE|CVAR_USERINFO)
CG_CVAR(cg_unlagged, "cg_unlagged", "1", CVAR_ARCHIVE|CVAR_USERINFO)
CG_CVAR(cg_depthSortParticles, "cg_depthSortParticles", "1", CVAR_ARCHIVE)
CG_CVAR(cg_bounceParticles, "cg_bounceParticles", "0", CVAR_ARCHIVE)
CG_CVAR(cg_consoleLatency, "cg_consoleLatency", "3000", CVAR_ARCHIVE)
CG_CVAR(cg_lightFlare, "cg_lightFlare", "3", CVAR_ARCHIVE)
CG_CVAR(cg_debugParticles, "cg_debugParticles", "0", CVAR_CHEAT)
CG_CVAR(cg_debugTrails, "cg_debugTrails", "0", CVAR_CHEAT)
CG_CVAR(cg_debugPVS, "cg_debugPVS", "0", CVAR_CHEAT)
CG_CVAR(cg_disableWarningDialogs, "cg_disableWarningDialogs", "0", CVAR_ARCHIVE)
CG_CVAR(cg_disableScannerPlane, "cg_disableScannerPlane", "0", CVAR_ARCHIVE)
CG_CVAR(cg_tutorial, "cg_tutorial", "1", CVAR_ARCHIVE)
CG_CVAR(cg_hudFiles, "cg_hudFiles", "ui/hud.txt", CVAR_ARCHIVE)

CG_CVAR(cg_painBlendUpRate, "cg_painBlendUpRate", "10.0", 0)
CG_CVAR(cg_painBlendDownRate, "cg_painBlendDownRate", "0.5", 0)
CG_CVAR(cg_painBlendMax, "cg_painBlendMax", "0.7", 0)
CG_CVAR(cg_painBlendScale, "cg_painBlendScale", "7.0", 0)
CG_CVAR(cg_painBlendZoom, "cg_painBlendZoom", "0.65", 0)

//TA: hack to get class an carriage through to UI module
CG_CVAR(ui_currentClass, "ui_currentClass", "0", 0)
CG_CVAR(ui_carriage, "ui_carriage", "", 0)
CG_CVAR(ui_stages, "ui_stages", "0 0", 0)
CG_CVAR(ui_dialog, "ui_dialog", "Text not set", 0)
CG_CVAR(ui_loading, "ui_loading", "0", 0)
CG_CVAR(ui_voteActive, "ui_voteActive", "0", 0)
CG_CVAR(ui_humanTeamVoteActive, "ui_humanTeamVoteActive", "0", 0)
CG_CVAR(ui_alienTeamVoteActive, "ui_alienTeamVoteActive", "0", 0)

CG_CVAR(cg_debugRandom, "cg_debugRandom", "0", 0)

CG_CVAR(cg_optimizePrediction, "cg_optimizePrediction", "1", CVAR_ARCHIVE)
CG_CVAR(cg_projectileNudge, "cg_projectileNudge", "1", CVAR_ARCHIVE)

//the following variables are created in other parts of the system,
//but we also reference them here

CG_CVAR(cg_buildScript, "com_buildScript", "0", 0) //force loading of all possible data amd error on failures
CG_CVAR(cg_paused, "cl_paused", "0", CVAR_ROM)
CG_CVAR(cg_blood, "com_blood", "1", CVAR_ARCHIVE)
CG_CVAR(cg_cameraOrbit, "cg_cameraOrbit", "0", CVAR_CHEAT)
CG_CVAR(cg_cameraOrbitDelay, "cg_cameraOrbitDelay", "50", CVAR_ARCHIVE)
CG_CVAR(cg_timescaleFadeEnd, "cg_timescaleFadeEnd", "1", 0)
CG_CVAR(cg_timescaleFadeSpeed, "cg_timescaleFadeSpeed", "0", 0)
CG_CVAR(cg_timescale, "timescale", "1", 0)
CG_CVAR(cg_scorePlum, "cg_scorePlums", "1", CVAR_USERINFO | CVAR_ARCHIVE)
CG_CVAR(cg_smoothClients, "cg_smoothClients", "0", CVAR_USERINFO | CVAR_ARCHIVE)
CG_CVAR(cg_cameraMode, "com_cameraMode", "0", CVAR_CHEAT)

CG_CVAR(cg_noTaunt, "cg_noTaunt", "0", CVAR_ARCHIVE)
CG_CVAR(cg_noProjectileTrail, "cg_noProjectileTrail", "0", CVAR_ARCHIVE)
CG_CVAR(cg_smallFont, "ui_smallFont", "0.2", CVAR_ARCHIVE)
CG_CVAR(cg_bigFont, "ui_bigFont", "0.5", CVAR_ARCHIVE)
CG_CVAR(cg_oldRail, "cg_oldRail", "1", CVAR_ARCHIVE)
CG_CVAR(cg_oldRocket, "cg_oldRocket", "1", CVAR_ARCHIVE)
CG_CVAR(cg_oldPlasma, "cg_oldPlasma", "1", CVAR_ARCHIVE)
CG_CVAR(cg_trueLightning, "cg_trueLightning", "0.0", CVAR_ARCHIVE)
//CG_CVAR(cg_pmove_fixed, "cg_pmove_fixed", "0", CVAR_USERINFO | CVAR_ARCHIVE)

#undef CG_CVAR
